### ISSUE TITLE
Update nightly feed info to Azure DevOps feed location

### ISSUE THREAD

**Issue by Eilon** [MicrosoftDocs/mobile-blazor-bindings#9]

**Comment by lachlanwgordon** [comment]
Are nightly feeds happening soon? I would use them.

**Comment by Eilon** [comment]
If I can push packages to GitHub packages, would that work for you? I've heard there are pros/cons but it might be the easiest for me to do.

**Comment by lachlanwgordon** [comment]
These can be used as a Nuget feed in Visual Studio, yeah? 

I've never used a GitHub packages feed before so I'm not sure what the cons are.

**Comment by Eilon** [comment]
Yup, it would just be another NuGet feed. One thing that's a bit more work with GitHub package feeds is that you _must_ authenticate to use them (well, just one time, anyway). There is no pure anonymous access to them.

You can read more here: https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages

**Comment by lachlanwgordon** [comment]
That's a shame, but not a deal breaker. I'm ok with authenicating.

**Comment by Eilon** [comment]
I think I will abandon that plan. I can't figure out how to push from Azure DevOps to GitHub Packages. Next try: MyGet.

**Comment by lachlanwgordon** [comment]
I've used public MyGets before and they work well. 

The Xamarin Forms repos recently moved away from MyGet and are now hosted on Azure Blob Storage and they just publish one shorttened url that forwards to blob storage for all the repos. https://aka.ms/xf-ci/index.json. I'm not sure why they moved but there was probably a reason. 

I didn't even know it was possible but this blog seems to say you can do it. https://emgarten.com/posts/how-to-host-a-nuget-v3-feed-on-azure-storage.

**Comment by Eilon** [comment]
OK try here: https://dotnet.myget.org/gallery/mobileblazorbindings-nightly

**Comment by lachlanwgordon** [comment]
This works. Hooray. Thank you!

**Comment by Eilon** [comment]
OK we might change from MyGet to a different, but just as easy public feed. I'll hold off on publicizing this much until that's settled. For right now you can use the MyGet feed, though.

**Comment by Eilon** [comment]
Final info is here: https://github.com/xamarin/MobileBlazorBindings/issues/28#issuecomment-669597642

I'll re-use this issue to track updating the docs to state the official feed location.

**Comment by Eilon** [comment]
Docs on using nightly feed are live! https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds
